### ISSUE TITLE
Install github release as created by CI

### ISSUE THREAD

**Issue by nbenn** [r-lib/remotes#132]
I'm sorry if I'm missing something here, but wouldn't it be nice if there was a way to directly install packages as prepared for example by travis using something like

```yaml
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: pkg_name*.t*gz
  skip_cleanup: true
  on:
    tags: true
```

This would make it possible to distribute binary packages via github, or bundle vignettes without checking them into git, etc.

Currently, `remotes::install_github("user/repo@*release")` fetches the full source code of the repo for the latest release ref and there seems to be no way of specifying a specific release file to be used instead.
