### ISSUE TITLE
install_github fails in Docker container when installing to non-standard user lib path

### ISSUE THREAD

**Issue by jonathan-g** [r-lib/remotes#536]
I'm running into a similar problem to #445 and #499, but unlike those cases, this shows up where the R_LIBS_USER path does exist and is writable and is added to `.libPaths` and I can successfully install to that path using `install_cran`, but `install_github` fails.

This applies in the context of a GitLab-CI build pipeline that runs in a docker container, where there is not a default user R library path in the user's home directory. Here, I only have write-access to the build directory, so I need to create an R library directory there and set `R_LIBS_USER` to point to that path.

Packages are successfully installed from CRAN to the user library at `R_LIBS_USER` using `install_cran`, but installing the GitHub version of the same package using `install_github` throws error about the destination directory not being writable.

This is a recent bug (or change in `install_github` behavior). In July I had a CI pipeline that used `remotes::install_github` and `remotes::install_gitlab` with no problem, and then my pipelines started failing in the last week or so (I suspect this is when the updated CRAN version of remotes made it into the docker container I was using for my pipelines, `rocker/verse:4.0.2`). The updating of `remotes` in the example below is just an example and I was not updating `remotes` in my production pipelines.

## Simple reproducible example:

The reproducible example exists as a publicly readable repository on GitLab: <https://gitlab.com/jonathan-g/test-ci>

### Create `.gitlab-ci.yml`

```
variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CRAN_REPOS: "https://cran.rstudio.com/"

image: rocker/verse

stages:
  - init

initialize:
  stage: init
  script:
    - pwd
    - mkdir -p $R_LIBS_USER
    - cp .gitlab-ci/.Rprofile ./.Rprofile
    - echo R_LIBS_USER = $R_LIBS_USER
    - ls -lah $R_LIBS_USER
    # Set force=TRUE so the example forces installation into R_LIBS_USER, to make sure that the installation works.
    - Rscript -e 'remotes::install_cran("remotes", repos = Sys.getenv("CRAN_REPOS"), force = TRUE, upgrade = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
    - ls -lah $R_LIBS_USER
    - Rscript -e 'library(remotes); sessionInfo()'
    - Rscript -e 'remotes::install_github("r-lib/remotes", force = FALSE, upgrade = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
    - ls -lah $R_LIBS_USER
  cache:
    key: lib
    paths:
      - $R_LIBS_USER
```

### create a `.Rprofile` file in the folder `.gitlab-ci/`

I put `.Rprofile` in a subdirectory because I don't want R to load the `gitlab-ci` version of `.Rprofile` when I run R in the project root directory.

.Rprofile is here to add `R_LIBS_USER` to the front of `.libPaths()`

```
local({
        lib_paths <- .libPaths()
        lib_paths <- c(Sys.getenv("R_LIBS_USER"), lib_paths)

        .libPaths(lib_paths)

        rep <- getOption("repos")
        rep["CRAN"] <-Sys.getenv("CRAN_REPOS")

        options(repos = rep)
})
```

## Expected Results

The CI process should first install the `remotes` package from CRAN to `R_LIBS_USER` and then install the newer development version from GitHub to `R_LIBS_USER`.

## Observed Results

The install from CRAN (using `install_cran`) works, but the install from GitHub (using `install_github`) fails with an error:
```
Error: Failed to install 'remotes' from GitHub:
  (converted from warning) 'lib = "/builds/jonathan-g/test-ci/ci/lib:/usr/local/lib/R/site-library:/usr/local/lib/R/library"' is not writable
```

## Complete log file from GitLab-CI:

Also available at https://gitlab.com/jonathan-g/test-ci/-/jobs/701505785

```
Running with gitlab-runner 13.3.0-rc1 (669fc507)
  on docker-auto-scale z3WU8uu-
Preparing the "docker+machine" executor
Using Docker executor with image rocker/verse ...
Pulling docker image rocker/verse ...
Using docker image sha256:6b36433c7137806dfe00c3e8c65f603c5eb6fc4ddf7547ca7e9f8ea6c65e3b4b for rocker/verse ...
Preparing environment
00:05
Running on runner-z3wu8uu--project-20718978-concurrent-0 via runner-z3wu8uu--srm-1598310104-a62a4d3e...
Getting source from Git repository
00:02
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/jonathan-g/test-ci/.git/
Created fresh repository.
Checking out fcbf4c22 as master...
Skipping Git submodules setup
Restoring cache
00:02
Checking cache for lib-2...
FATAL: file does not exist                         
Failed to extract cache
Executing "step_script" stage of the job script
$ pwd
/builds/jonathan-g/test-ci
$ mkdir -p $R_LIBS_USER
$ cp .gitlab-ci/.Rprofile ./.Rprofile
$ echo R_LIBS_USER = $R_LIBS_USER
R_LIBS_USER = /builds/jonathan-g/test-ci/ci/lib
$ ls -lah $R_LIBS_USER
total 16K
drwxr-xr-x. 2 root root 4.0K Aug 24 23:04 .
drwxr-xr-x. 3 root root 4.0K Aug 24 23:04 ..
$ Rscript -e 'remotes::install_cran("remotes", repos = Sys.getenv("CRAN_REPOS"), force = TRUE, upgrade = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
Installing 1 packages: remotes
trying URL 'https://cran.rstudio.com/src/contrib/remotes_2.2.0.tar.gz'
Content type 'application/x-gzip' length 145553 bytes (142 KB)
==================================================
downloaded 142 KB
* installing *source* package ‘remotes’ ...
** package ‘remotes’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (remotes)
The downloaded source packages are in
	‘/tmp/Rtmp07wJC7/downloaded_packages’
$ ls -lah $R_LIBS_USER
total 24K
drwxr-xr-x. 3 root root 4.0K Aug 24 23:04 .
drwxr-xr-x. 3 root root 4.0K Aug 24 23:04 ..
drwxr-xr-x. 7 root root 4.0K Aug 24 23:04 remotes
$ Rscript -e 'library(remotes); sessionInfo()'
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS
Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblasp-r0.3.8.so
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] remotes_2.2.0
loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2   
$ Rscript -e 'remotes::install_github("r-lib/remotes", force = FALSE, upgrade = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo r-lib/remotes@HEAD
✔  checking for file ‘/tmp/RtmpPbO2rr/remotes6052cf49a6/r-lib-remotes-5a546ad/DESCRIPTION’
─  preparing ‘remotes’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘remotes_2.2.0.9000.tar.gz’
   
Error: Failed to install 'remotes' from GitHub:
  (converted from warning) 'lib = "/builds/jonathan-g/test-ci/ci/lib:/usr/local/lib/R/site-library:/usr/local/lib/R/library"' is not writable
Execution halted
ERROR: Job failed: exit code 1
```
