### ISSUE TITLE
Ability to pass auth_token to install_deps() function 

### ISSUE THREAD

**Issue by aylapear** [r-lib/remotes#554]
Our GitHub Actions were always failing due to an authentication error when they had to install dependencies from private repositories. The authentication error was caused from us naming the GITHUB_TOKEN as GITHUB_PAT in the environment variables (see Code that Failed example). We were able to determine this is because `install_deps()` must have the PAT named as GITHUB_PAT (see Code that Passed example). 

The functionality of `install_github()` allows you to name the PAT yourself within your environment variables and you just have to pass it under the variable of auth_token. 

```
install_github("poissonconsulting/chktemplate", auth_token=Sys.getenv("NEW_PAT"))
```

It would be great if this functionality could be extended to `install_deps()` like it is in `install_github()` so you could write `install_deps(auth_token=Sys.getenv("NEW_PAT"))`

<details open>
<summary>Code that Failed</summary>

```
name: R-CMD-check

jobs:
  R-CMD-check:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

> Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
> cannot open URL 'https://api.github.com/repos/poissonconsulting/chktemplate/contents/DESCRIPTION?ref=HEAD'
> Calls: saveRDS ... github_DESCRIPTION -> download -> base_download -> base_download_headers
> Execution halted
> Error: Process completed with exit code 1.
```

</details>

<br>
</br>

<details open>
<summary>Code that Passed</summary>

```
name: R-CMD-check

jobs:
  R-CMD-check:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_PRIVATE_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
```
</details>
